ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: >
      bundle install --without production &&
      rails db:migrate
    command: >
      rails server
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
vscode:
  extensions:
    - bung87.rails@0.16.4:aHz6MDL2HyKKahKWJ9KF2g==